  
version: '3.5'
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - database
    environment:
      - FLASK_APP=src/app.py
    env_file: database.conf

volumes:
  db_volume: